### ISSUE TITLE
ارور

### ISSUE THREAD

**Issue by xematin** [Azumi67/Chisel_multipleServers#20]
Traceback (most recent call last):
  File "/dev/fd/63", line 3280, in <module>
  File "/dev/fd/63", line 211, in main_menu
  File "/dev/fd/63", line 786, in chisel_tcp_ip6
  File "/dev/fd/63", line 1341, in kharej_ipv6
  File "/dev/fd/63", line 910, in chisel_mnu
  File "/dev/fd/63", line 64, in display_loading
AttributeError: 'function' object has no attribute 'time'

**Comment by Azumi67** [comment]
fixed

**Comment by Azumi67** [comment]
check again. it was due to adding edit timer.

**Comment by xematin** [comment]
پایتون ورژن قدیمی نصب کردم اوکی شد ارور ولی بعد از تونل کردن مشکل سرور ایرانم حل نشد! 3 بار تانل زدم با روش مختلف کار نمیکنه! میتونم ایپی و یوزر پس بفرستم چکش کنید ؟ پول پس نمیده 😔

**Comment by Azumi67** [comment]
نمیدونم من از این کارها نمیکنم. حالا فردا بعد از ظهر پیام بدید در حد توان کمکتون میکنم.

**Comment by xematin** [comment]
خیلی ممنونم! ایدی تلگرامم میزارم یا شما بزارید! 
@MentaMentor
